### ISSUE TITLE
Bad exit status with multipy list

### ISSUE THREAD

**Issue by Cito** [akheron/multipy#2]
The list() function should end with "return 0". Otherwise, since Bash exits with the exit status from the last command, "multipy list" will exit with a status of 1 unless all Python versions are installed. Maybe other commands also need to set a proper exit value.

**Comment by akheron** [comment]
Thanks for reporting this issue.

Fixed in commit e6ccb087833fe0432491. Somehow the GitHub issue machinery failed to close this issue properly after I pushed the change.
